### ISSUE TITLE
clean BasicManagement error handling

### ISSUE THREAD

**Issue by jku** [jku/rygel#4]
Filing a few issues to remind myself...

BasicManagementTestError is now used for two different purposes: it should be two different errors.

Alternatively we could maybe get rid of the exception in init: I _think_ the check for hostname  is not very useful since there's lots of invalid hostname values we don't check: this could be handled just like all the other error cases should be: by creating a result with an "Error_something" value

**Comment by jku** [comment]
PR in issue #10 will fix this, IMO

**Comment by cguiraud** [comment]
fixed by  PR #10.
